# Set OS envvar
if [[ $(uname) == 'Linux' ]]; then
    export OS="linux"
elif [[ $(uname) == 'Darwin' ]]; then
    export OS="osx"
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export AWESOME_CONFIG=$HOME/.config/awesome
export EDITOR='vim'
export ZSH_CUSTOM=$ZSH/custom
export ZSH_THEME="personal"
export RPROMPT_MODE=2
export USER_BIN="$HOME/bin"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home"
export M2_HOME="$USER_BIN/apache-maven-3.6.3/bin"
export DOCKER_DIR="$HOME/docker-containers"

# Add personal exports to __path where appropriate
export PATH=$PATH:$USER_BIN:$JAVA_HOME:$M2_HOME

if [[ -f ${HOME}/.private-zprofile ]]; then
    . ${HOME}/.private-zprofile
fi
